// <auto-generated />
namespace MVCProject_Nazmul.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class N1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(N1));
        
        string IMigrationMetadata.Id
        {
            get { return "202403250430287_N1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
